spring:
  application:
    name: MyBookSearchMS
    
server:
    port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true

logging:
    level:
        root: INFO
    pattern:
        console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
